Jenkinsfile
Please copy the timeout setting to all branches (and adjust if necessary).
Context: I have noticed builds running for 23 hours and just hanging. This unnecessarily binds resources.
=> Use timeout to avoid long blocking builds

CHANGELOG.md, tests/test_proxy_auxiliary.py
multiprocessing Queues are note reliable so switch to queue.queue instead inside unittest.
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue.empty
=> test(test_proxy_auxiliary.py): make test reliable

docs/getting_started/config_file.rst, examples/dummy_env_var.yaml, src/pykiso/config_parser.py, tests/test_config_parser.py
Linked to: https://github.com/eclipse/kiso-testing/issues/21
Allow to set default values for env variables in case they are not found with the following syntax:
ENV{ENABLE_KEY_EXCHANGE=True}
=> add the possibility to set default values to ENV variables in the yaml config files

Pipfile, README.md, setup.py, src/pykiso/auxiliary.py, src/pykiso/cli.py, src/pykiso/exceptions.py, src/pykiso/interfaces/mp_auxiliary.py, src/pykiso/interfaces/simple_auxiliary.py, src/pykiso/interfaces/thread_auxiliary.py, src/pykiso/lib/auxiliaries/instrument_control_auxiliary/instrument_control_auxiliary.py, src/pykiso/test_coordinator/test_case.py, src/pykiso/test_coordinator/test_execution.py, tests/test_auxiliary.py, tests/test_dut_auxiliary.py, tests/test_simple_auxiliary.py
- raise the brand new AuxiliaryCreationError exception when the aux instance creation failed
- remove unused timeout decorator
- add --fail-fast flag to cli
=> raise an exception when auxiliary failed at instance creation

tests/test_cc_proxy.py, tests/test_proxy_auxiliary.py
Replaced it with empty() method in the tests.
=> fix: qsize() not available for macos x

CHANGELOG.md, docs/introduction/integration_test.rst, examples/test_suite_1/test_suite_1.py, pyproject.toml, src/pykiso/test_coordinator/test_result.py, src/pykiso/test_coordinator/test_suite.py, tests/test_test_suite.py
If multiple suite_ids exist in the pykiso run, only suite child tests with the same suite_id will be skipped when an exception is risen in the SuiteSetup
=> fix: skip suite tests when setup fails

.pre-commit-config.yaml, src/pykiso/lib/connectors/cc_rtt_segger.py
Fix the issue of mix log with 2 CCRttSegger : the logger is the same object for both connector.
=> fix: change logger name if a serial number is specified

.pre-commit-config.yaml, src/pykiso/test_coordinator/test_suite.py, src/pykiso/test_result/text_result.py, tests/test_test_suite.py
Fix skipping test cases if a test suite setup fails by looking if an error occurred in the test and then storing it.
I use `result.error_occured` because it is how a test is considered failed or not : https://github.com/eclipse/kiso-testing/blob/master/src/pykiso/test_result/text_result.py#L199
=> fix: fix skip test cases of a test suite if a test suite setup fails

docs/whats_new/version_ongoing.rst, src/pykiso/logging_initializer.py
Store activated loggers so that they won't be deactivated by a latter imported auxiliary that does not list this logger in its `activate_log` config param
=> feat: store activated loggers globally

docs/auxiliaries/index.rst, docs/auxiliaries/ykush_auxiliary.rst, docs/modules_usage/ykush_control.rst, docs/whats_new/version_ongoing.rst, examples/test_suite_ykush/test_ykush.py, examples/ykush.yaml, poetry.lock, pyproject.toml, src/pykiso/lib/auxiliaries/ykush_auxiliary.py, tests/test_ykush_auxiliary.py
Auxiliary that connect to an Ykush device : https://www.yepkit.com/products/ykush .
The auxiliary give the possibility to switch ports on and off individually and get the state of the port.
=> feat: Implement ykush auxiliary

docs/whats_new/version_0_21_2.rst, pyproject.toml, src/pykiso/lib/auxiliaries/instrument_control_auxiliary/instrument_control_auxiliary.py, src/pykiso/test_setup/dynamic_loader.py, tests/test_dynamic_loader.py, tests/test_instrument_control_auxiliary.py
- Decode bytes received from cchannel to strings as previously returned
- Specify another error case in dynamic loader to improve error reporting
- Bump version to 0.21.2
=> fix: decode received bytes in instrument_control_auxiliary

.pre-commit-config.yaml, docs/advanced_usage/advanced_config_file.rst, docs/modules_usage/uds_auxiliary.rst, docs/whats_new/index.rst, docs/whats_new/version_0_19_3.rst, docs/whats_new/version_ongoing.rst, src/pykiso/lib/auxiliaries/mp_proxy_auxiliary.py, src/pykiso/lib/auxiliaries/proxy_auxiliary.py, src/pykiso/lib/connectors/cc_mp_proxy.py, src/pykiso/lib/connectors/cc_pcan_can.py, src/pykiso/lib/connectors/cc_proxy.py, src/pykiso/test_setup/config_registry.py, tests/test_config_registry_and_test_execution.py, tests/test_proxy_auxiliary.py
This implements auto start & stop capabilities for the ProxyAuxiliary:
- when the first CCProxy is opened and the ProxyAuxiliary isn't started yet, start it
- when the last CCProxy is closed and the ProxyAuxiliary is running, stop it
- if all auxiliaries are marked with `auto_start: False` in the config, apply this to the created ProxyAuxiliary as well
-> Goal is to entirely hide the proxy from the user as he won't be able to access it anymore in case of an automatic proxy creation
=> feat: allow proxy auto start and stop

src/pykiso/tool/testrail/cli.py
Fix two bugs:
* CLI did not work at all
* Crash when no test cases could be matched. Print an error and exit instead.
=> fix: Testrail CLI

src/pykiso/interfaces/dt_auxiliary.py, src/pykiso/lib/auxiliaries/proxy_auxiliary.py, src/pykiso/lib/connectors/cc_pcan_can.py, src/pykiso/lib/connectors/cc_proxy.py, src/pykiso/logging_initializer.py, tests/test_cc_pcan_can.py, tests/test_logging_initializer.py
Some inconsistencies were found and this PR tackles them:
- CCPcanCan log the error with info level instead of debug in case of a CanError
- CCProxy set the queue to None when closed to avoid overflowing it when not needed
- Logging update log_options after manipulating the used log_path
- DTAuxiliaryInterface log when an auxiliary is already started/stopped
=> Apply various found fixes and improvements

src/pykiso/test_coordinator/test_case.py, src/pykiso/test_result/assert_step_report.py, src/pykiso/test_result/templates/report_template.html.j2, tests/test_assert_step_report.py, tests/test_test_case.py
- Fix wrong result in step report
- Assertion for retry test are now separated in different tables for every test and only the last attempt is visible for the user but he can toggle to see all the information of the test.
=> fix: fix step report show wrong result

pyproject.toml
Addresses https://github.com/eclipse/kiso-testing/issues/313
-> junit report is complete again: https://ci.eclipse.org/kiso-testing/job/kiso-testing/job/PR-321/1/testReport/
=> fix: add junitxml option to default pytest options

src/pykiso/cli.py, src/pykiso/logging_initializer.py, src/pykiso/test_setup/config_registry.py, tests/conftest.py, tests/test_config_registry_and_test_execution.py, tests/test_logging_initializer.py
- flatten log path assignment in cli.py
- add a context manager to ConfigRegistry to ensure proper cleanup
- re-enable previously deactivate loggers in initialize_loggers
=> fix: re-enable active loggers and add context manager for ConfigRegistry

src/pykiso/config_parser.py, tests/test_config_parser.py
pkg_resources was still present somewhere and takes up to 5s to be entirely loaded -> replaced with importlib.metadata or the backport importlib_metadata
Coverage check is failing because of the importlib.metadata import (has to be handled differently for py3.7), but this is already tested by the jenkins pipeline running the unit tests with py3.7
=> feat: replace pkg_resources with importlib.metadata for faster load time

src/pykiso/logging_initializer.py, src/pykiso/test_coordinator/test_case.py, src/pykiso/test_result/xml_result.py, tests/test_logging_initializer.py, tests/test_test_case.py
When running pykiso without verbose but with the junit option provided, the internal logs were no longer displayed in the provided log file
=> fix: enable internal file logging when junit option is provided

.pre-commit-config.yaml, src/pykiso/test_coordinator/test_execution.py, tests/test_config_registry_and_test_execution.py
Improve testsuite validation.
If test files are sleceted in child folders child folders must have an __init__ file. 
Support check for nested child folders.
Print error when init file is missing
=> feat: improve testsuite validation

src/pykiso/interfaces/dt_auxiliary.py, tests/test_dt_auxiliary_interface.py
When a callback executed in _receive_message calls run_command while the auxiliary is being deleted, this run_command call never gets to acquire the lock (already acquired by delete_instance in the main thread) and _receive_message never terminates either.
This leads to deadlocks on delete_instance calls.
Solution is to add an event acting as a guard and preventing run_command to try and acquire the lock while the auxiliary is being deleted
=> fix: add event to avoid deadlocks on run_command calls

src/pykiso/test_coordinator/test_execution.py, tests/test_config_registry_and_test_execution.py
Prevent multiple execution when -p flag is given through the cli. 
Happens when multiple suite_dir are given in the config file.
=> fix: multiple execution if file pattern is provided

examples/record_rtt_segger.yaml, src/pykiso/lib/connectors/cc_rtt_segger.py, tests/test_cc_rtt_segger.py
Fix issue if Block Adress ist set to NULL in yaml 
Fix logging when rtt receives undecodeble bytes
=> fix: undecodeable bytes received from rtt segger

src/pykiso/lib/connectors/flash_jlink.py, tests/test_flash_jlink.py
Docs said call erase before flash() method but not for method flash_file (:
Seems to work again now.
=> fix: jlink flash

src/pykiso/pytest_plugin/logging.py, tests/pytest_plugin/conftest.py, tests/pytest_plugin/test_collection.py, tests/pytest_plugin/test_plugin.py
The refactoring of the logging mechanism broke the pytest plugin's logging configuration.
Running `pytest dummy.yaml --log-cli-level INFO -vv` now shows the INTERNAL_INFO live logs in the console
=> fix: apply internal log level to pytest logger

src/pykiso/test_setup/config_registry.py
Fix yaml with 2 auxiliaries which are using the same connector
config item of one auxiliary is set to None with the ~ character
It was raising a TypeError since the config is None:
=> fix: two auxiliaries with the same connector and the config is None

docs/whats_new/version_ongoing.rst, src/pykiso/lib/connectors/cc_pcan_can/cc_pcan_can.py, tests/test_cc_pcan_can.py, tests/test_cc_virtual_can.py
=> feat: merge trc into one file can be disabled

docs/whats_new/version_ongoing.rst, src/pykiso/lib/connectors/cc_pcan_can/cc_pcan_can.py, tests/test_cc_pcan_can.py
Add the possibility to stop and start pcan trace and to specify name of the logfile wanted.
Since the user can specify a new path when he starts the pcan trace he can choose a different repository, I added a dictionary that has for key the directory path and as value a list of all the file_name for this repository to be able to rename all of them or to merge them depending on the logic wanted.
=> feat: add start stop can trace

.github/workflows/codecov.yml, .github/workflows/verification_validation.yml, Jenkinsfile
It feels a little bit paradoxical to keep the Jenkins running in parallel but I want to see how both are performing before we switch one off.
I switched Jenkins release off so that we do not have conflicts with the github-actions.
In addition, it seems like codecov had some changes in the past and we are not able to upload anymore to it (since 2 months...). I fixed this issue too
=> ci: fix codecov & release secrets

docs/auxiliaries/can_auxiliary.rst, examples/test_can/test_can.py, src/pykiso/lib/auxiliaries/can_auxiliary/__init__.py, src/pykiso/lib/auxiliaries/can_auxiliary/can_auxiliary.py, tests/test_can_aux.py
Add a context manager to be able to receive a message after a send operation in case the response is too fast.
=> feat: add context manager to receive can message

docs/connectors/CChannels/cc_pcan_can.rst, src/pykiso/lib/connectors/cc_pcan_can/cc_pcan_can.py, src/pykiso/test_coordinator/test_execution.py, src/pykiso/test_setup/dynamic_loader.py, tests/test_cc_pcan_can.py, tests/test_config_registry_and_test_execution.py
Add the possibility for the user to get one trace can per TestCase or for every test run from the configuration of the `CCPCanCan` by adding one parameter.
=> feat: add one trace file per test case or test run

src/pykiso/cli.py, src/pykiso/test_coordinator/test_execution.py, tests/test_cli.py
Solves the issue when users spawns threads and Pykiso keeps the python process open when user threads are unresolved.
=> feat: force pykiso to close if threads are blocking

pyproject.toml, src/pykiso/lib/auxiliaries/proxy_auxiliary.py
Fix the case when using the original proxy setup (proxy aux created and CCProxy in the yaml) , an auxiliary is started then the  `_open_connections` will be 1 then this auxiliary is stopped `_open_connections` will be 0 which will trigger the `delete_instance` that will then close the connector even if other auxiliaries still have their channel open.
It will then raise an issue when trying to send a message with an other auxiliary since it is closed when it should be opened.
=> fix: fix side effect when one auxiliary get suspended

src/pykiso/lib/connectors/cc_tcp_ip.py, tests/test_cc_tcp_ip.py
When an auxiliary such as `InstrumentControlAuxiliary` is `suspend`ed then `resume`d, its channel has its methods `_cc_close`, then `_cc_open` called. 
The `CCTcpip` connector currently doesn't support that: once `_cc_close` has been called, `_cc_open` cannot be called anymore. This is because `socket.socket` does not support reopening a closed socket. 
The changes here create the socket in `_cc_open`, allowing multiple `_cc_open` / `_cc_close` cycles. 
Relevant test (`tests/test_cc_tcp_ip.py`) has been updated, because it depended on using various methods of `CCTcpip` without first calling `_cc_open`. This use case should not happen in the real world, and doesn't work anymore now that the socket is only created in `_cc_open`.
=> Fix resuming CCTcpip

pyproject.toml, src/pykiso/test_coordinator/test_case.py, src/pykiso/test_result/assert_step_report.py, tests/test_assert_step_report.py
Current step report result for following test : 
Give the following result : 
Because the self.assertEqual calls other assert function inside unittest so now if the function is called inside unittest.case we just execute the function normally.
There was also issue if users were using deprecated function then the variable name was not found since the function name will be `deprecated_fun` and the signature was not defined in the decorator used by unittest to deprecate the function.
So now overwrite the deprecated function with a decorator that keeps the signature and retry to find variable name by using the depecrated function name.
=> fix: step report issue with TypeError

pyproject.toml, src/pykiso/lib/connectors/cc_socket_can/socketcan_to_trc.py, tests/test_socketcan_to_trc.py
Fix strategy trace file when an auxiliary is suspended or stopped in a test.
=> Fix socket can strategy trace file

docs/advanced_usage/profiling.rst
=> chore: cleanup docs

pyproject.toml, src/pykiso/lib/auxiliaries/udsaux/uds_server_auxiliary.py, tests/test_uds_server_auxiliary.py
Fix receive function to check multiple messages instead of checking only the first one.
Because the CanTp that we use from the python-uds package use this receive function to wait for a flow control for example and if we return None because the first message is for a different CAN ID it will raise a TimeoutError : 
https://github.com/eclipse-kiso-testing/kiso-testing-python-uds/blob/master/uds/uds_communications/TransportProtocols/Can/CanTp.py#L237-L240
=> fix: receive function in uds server auxiliary

pyproject.toml, src/pykiso/logging_initializer.py, tests/test_logging_source_location.py
fix internal logging source information:
Otherwise it will always be:    logging_initializer:183
Example:
2025-07-30 12:46:27,752 [INTERNAL_INFO] logging_initializer:183: Auxiliary 'bla_aux' is not using import magic mechanism (pre-loaded)
2025-07-30 12:46:30,316 [INTERNAL_INFO] logging_initializer:183: Auxiliary 'blub_aux' is not using import magic mechanism (pre-loaded)
=> fix: logging source information

.gitignore, docs/modules_usage/uds_auxiliary.rst, docs/whats_new/version_1_6_0.rst, examples/uds.yaml, pyproject.toml, src/pykiso/lib/auxiliaries/udsaux/uds_auxiliary.py
To send a UDS message, a common way is the method `UdsAuxiliary.send_uds_raw`, with the following signature:
```python
def send_uds_raw(
self,
msg_to_send: Union[bytes, List[int], tuple],
timeout_in_s: float = 6,
response_required: bool = True,
) -> Union[UdsResponse, bool]:
...
```
On error, this method returns `False`, which means we lose the detail on the exact problem (and is un-pythonic). _Unless_ the issue is because a response is required, but none was received, which is inconsistent.
In fact, most existing client actually expect the method to always return an exception on error, or return a valid `UdsResponse` object.
This approach was implemented by the new `UdsAuxiliary.send_uds` function, which is almost the same:
```python
@overload
def send_uds(
self,
msg_to_send: …
```
=> fix: Add 'UdsAuxiliary.send_uds' with clearer return type to replace 'send_uds_raw'
