CHANGELOG.md
Pipfile
setup.py
src/pykiso/lib/connectors/cc_pcan_can.py
src/pykiso/lib/connectors/cc_vector_can.py
tests/test_cc_pcan_can.py
tests/test_cc_rtt_segger.py
tests/test_cc_vector_can.py

- Add CAN connectors
- Add Unittests
Documentation already available in connectors.rst

Add CAN connectors

---

ci/Dockerfile

Add node and npm to the docker container..

update Dockerfile to build vsc plugin

---

.github/workflows/codecov.yml

Based on the inputs of https://github.com/codecov/example-python/blob/master/.github/workflows/ci.yml, I tried to create the action

draft github-action for codecov

---

CHANGELOG.md
Jenkinsfile
Pipfile
setup.py
templates/changelog/changelog.jinja2

will add uptime library for pcan timestamp
* changelog tool currently broke so ignore Changelog

feat: add uptime for pcan inside python-can

---

CHANGELOG.md
docs/advanced_features/access_config.rst
docs/advanced_features/index.rst
docs/getting_started/config_file.rst
docs/index.rst
docs/whats_new/index.rst
docs/whats_new/version_0_16_0.rst

Add section what's new to docs

docs: add section whats new

---

docs/introduction/integration_test.rst
docs/whats_new/index.rst
docs/whats_new/version_0_17_0.rst

Add missing whats new for 0.17.0

docs: Add whats new for 0.17.0

---

docs/introduction/integration_test.rst

I realised we were missing our quality goals. I tried to document them here.

docs: Add quality goals

---

CHANGELOG.md
docs/whats_new/index.rst
docs/whats_new/version_0_18_0.rst
docs/whats_new/version_ongoing.rst
pyproject.toml

feat: make release 0.18.0

---

docs/introduction/integration_test.rst
docs/remote_test/remote_test.rst
examples/test_suite_1/test_suite_1.py
src/pykiso/cli.py
src/pykiso/test_coordinator/test_message_handler.py
tests/test_test_case.py

So now behaviour is as in the docs :)

fix: multiple yaml logging

---

CHANGELOG.md
README.md
docs/getting_started/config_file.rst
docs/introduction/integration_test.rst
docs/whats_new/version_ongoing.rst
pyproject.toml
src/pykiso/cli.py
src/pykiso/test_coordinator/test_execution.py
tests/test_cli.py
tests/test_config_registry_and_test_execution.py
tests/test_message.py

Select agnostic tags from cli
example
pykiso -c .\examples\dummy.yaml branch_level nightly,daly

feat: agnostic tags

---

dependabot.yml
poetry.lock
pyproject.toml

Wrote the dependabot configuration file to manage our dependencies

feat: add dependabot to manage our fixed dependencies

---

CHANGELOG.md
examples/pytest/dummy/conftest.py
src/pykiso/tool/pykiso_to_pytest/templates/conftest_template.jinja2

Rerun pykitest to update the example.
Pytest run was succesfull with 
>pytest examples/pytest/dummy/ --log-cli-level=DEBUG

fix: update pykitest example

---

docs/index.rst
docs/step_report.rst
pyproject.toml
src/pykiso/cli.py
src/pykiso/test_coordinator/assert_step_report/__init__.py
src/pykiso/test_coordinator/assert_step_report/assert_step_report.py
src/pykiso/test_coordinator/assert_step_report/report_template.css
src/pykiso/test_coordinator/assert_step_report/report_template.html.j2
src/pykiso/test_coordinator/test_execution.py
src/pykiso/test_coordinator/test_result.py
tests/test_assert_step_report.py

This adds the step report feature from Yoanns branch, rebased to the current master.

feat: Step report

---

CHANGELOG.md
poetry.lock
pyproject.toml
src/pykiso/test_coordinator/assert_step_report/assert_step_report.py
tests/test_cli.py

Please check what else should be updated for 0.19.1

chore(deps): Update click

---

README.md
docs/advanced_usage/advanced_tests.rst
docs/getting_started/basic_config_file.rst
docs/whats_new/version_ongoing.rst
src/pykiso/cli.py
src/pykiso/test_coordinator/test_execution.py
tests/test_config_registry_and_test_execution.py

Add feature to select testcases with an regex by passing the flag -t or --tc-filter to the pykiso cli

feat: select test case with regex

---

CHANGELOG.md
docs/getting_started/basic_tests.rst
src/pykiso/test_coordinator/test_case.py

Just add a little section regarding suite/case id default value and usage.

Ensure default behaviour when (suite case) id is 0

---

src/pykiso/test_result/assert_step_report.py
src/pykiso/test_result/templates/report_template.css
src/pykiso/test_result/templates/report_template.html.j2
tests/test_assert_step_report.py

Tests are now foldable items.
If tests have failed they are open by default.
Also removed whitespaces when html gets generated

feat: add step report folding

---

Jenkinsfile
ci/Dockerfile
tox.ini

@sebastianpfischer pls rebuild the docker container for me an upload it.
Jenkins stage will Follow

feat: add tox

---

src/pykiso/test_coordinator/test_execution.py
src/pykiso/test_result/multi_result.py
src/pykiso/test_result/xml_result.py
tests/test_multi_result.py
tests/test_xml_result.py

Creation of a result class in order to be able to create different Result types within one Pykiso run.

feat: implement multi test result class

---

tests/test_record_auxiliary.py

fix: fixing record auxiliary unittest

---

tests/test_config_parser.py
tests/test_config_registry_and_test_execution.py
tests/test_record_auxiliary.py

test: fix unittest issues

---

src/pykiso/test_result/assert_step_report.py
src/pykiso/test_result/templates/report_template.html.j2
tests/test_assert_step_report.py

Add unexpected errors traceback under the table created by the step report and fails the the test if an error was raised in the test.

feat: step report handler errors raised

---

.github/workflows/codecov.yml

I reverted the code in #266 that broke the codecov github job

bugfix[codecov]: revert container version

---

docs/whats_new/version_ongoing.rst
src/pykiso/lib/connectors/cc_pcan_can.py
src/pykiso/lib/connectors/cc_vector_can.py
tests/test_cc_pcan_can.py
tests/test_cc_vector_can.py

added the timestamp to the recevied pcan and vector can message

---

README.md
docs/advanced_usage/how_to_change_logger_class.rst
docs/advanced_usage/index.rst
src/pykiso/cli.py
src/pykiso/logging_initializer.py
src/pykiso/test_coordinator/test_message_handler.py
tests/test_logging_initializer.py

Add the possibility to change the logger class with the CLI.

feat: change logger class for the test

---

docs/whats_new/version_ongoing.rst
src/pykiso/lib/connectors/cc_serial.py
tests/test_cc_serial.py

feat: added the possibility to connect via serial number

---

Jenkinsfile
docs/whats_new/index.rst
docs/whats_new/version_0_27_0.rst
docs/whats_new/version_ongoing.rst
pyproject.toml
src/pykiso/pytest_plugin/logging.py

Make Release and fixing the Jekins Pipe.

Make Release 0.27.0

---

src/pykiso/auxiliary.py

Fix a rare case where the `join()` function could be called before the thread is started.

fix: stop rx task call before start rx task is called

---

pyproject.toml

feat: make release 0.28.1

---

src/pykiso/logging_initializer.py

Activate internal level for logger if verbose is active.

fix: log level when verbose is activated

---

pyproject.toml

feat: make release 0.29.3

---

pyproject.toml
src/pykiso/lib/connectors/cc_pcan_can/cc_pcan_can.py
src/pykiso/test_coordinator/test_execution.py
tests/test_cc_pcan_can.py
tests/test_config_registry_and_test_execution.py

When the cc_pcan is opened multiple times, it will not raise an error.

fix: fix issue of connector

---

docs/tools/xray.rst
poetry.lock
pyproject.toml
src/pykiso/test_coordinator/test_case.py
src/pykiso/tool/xray/cli.py
src/pykiso/tool/xray/xray.py
tests/test_cli.py

Add possibility to rename test execution ticket created.
Add file and repository support.

feat: add improvement for xray

---

pyproject.toml

With this pull request, we mark the release of Version 1.0.0, a significant milestone in the journey of this project. This accomplishment is the result of the collective efforts of an amazing group of contributors, collaborators, and supporters.
I’d like to extend a heartfelt thank you to everyone who:
-   Contributed code, ideas, and feedback.
-   Reviewed pull requests with diligence and care.
-   Reported issues and helped identify improvements.
-   Supported the project in any way, big or small.
Every commit, discussion, and contribution has been a building block leading to this milestone. It’s been an incredible journey, and this release stands as a testament to what we can achieve together.
Thank you all! 🎉👏

feat: Release 1.0.0

---

examples/test_suite_1/test_suite_1.py

Restore test which was accidentality commited

fix: restore test_suite_1

---

pyproject.toml

fix: project version

---

src/pykiso/test_result/assert_step_report.py
tests/test_assert_step_report.py

Improve the html step reports by supporting the parameterized tests

Feature/ html step report supports parameterized tests

---

pyproject.toml

chore: update project version
